# Generated by Django 5.2.1 on 2025-05-29 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='prev_degree_gpa',
            new_name='prev_degree1_gpa',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='prev_degree_name',
            new_name='prev_degree1_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='prev_degree_university',
            new_name='prev_degree1_university',
        ),
        migrations.AddField(
            model_name='student',
            name='prev_degree2_gpa',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='prev_degree2_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='prev_degree2_university',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
