# Generated by Django 5.2 on 2025-06-25 10:16

import DB.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Campus",
            fields=[
                (
                    "id",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("campus_name", models.CharField(max_length=100, unique=True)),
                ("location", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "dept_id",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("dept_name", models.CharField(max_length=100, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("programme_code", models.CharField(max_length=20)),
                ("batch", models.IntegerField()),
                ("paper_code", models.CharField(max_length=20)),
                ("paper_title", models.CharField(max_length=150)),
                (
                    "semester",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(8),
                        ],
                    ),
                ),
                ("sequence", models.IntegerField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Theory", "Theory"),
                            ("Practical", "Practical"),
                            ("Core", "Core"),
                            ("Elective", "Elective"),
                        ],
                        max_length=20,
                    ),
                ),
                ("credits", models.DecimalField(decimal_places=1, max_digits=3)),
                ("cie_max", models.IntegerField()),
                ("cie_max_atp", models.IntegerField(blank=True, null=True)),
                ("cie_max_psn", models.IntegerField(blank=True, null=True)),
                ("cie_max_brn", models.IntegerField(blank=True, null=True)),
                ("cie_max_ndg", models.IntegerField(blank=True, null=True)),
                ("ese_max", models.IntegerField()),
                ("ese_max_atp", models.IntegerField(blank=True, null=True)),
                ("ese_max_psn", models.IntegerField(blank=True, null=True)),
                ("ese_max_brn", models.IntegerField(blank=True, null=True)),
                ("ese_max_ndg", models.IntegerField(blank=True, null=True)),
                ("cie_wtg", models.DecimalField(decimal_places=2, max_digits=5)),
                ("ese_wtg", models.DecimalField(decimal_places=2, max_digits=5)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "unique_together": {("programme_code", "batch", "paper_code")},
            },
        ),
        migrations.CreateModel(
            name="Faculty",
            fields=[
                (
                    "faculty_id",
                    models.CharField(
                        max_length=4,
                        primary_key=True,
                        serialize=False,
                        validators=[DB.models.validate_fixed_length],
                    ),
                ),
                ("dp_key", models.UUIDField(blank=True, default=None, null=True)),
                ("dob", models.DateField(blank=True, null=True)),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("gender", models.CharField(max_length=10)),
                ("mobile", models.CharField(max_length=15, unique=True)),
                ("qualification", models.CharField(blank=True, max_length=100)),
                ("status", models.CharField(default="active", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "campus",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="campus_faculty",
                        to="DB.campus",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="faculty",
                        to="DB.department",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="department",
            name="hod",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="headed_department",
                to="DB.faculty",
            ),
        ),
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("programme_code", models.CharField(max_length=20)),
                ("batch", models.IntegerField()),
                ("programme_short_name", models.CharField(max_length=100)),
                ("programme_full_name", models.CharField(max_length=255)),
                (
                    "total_semesters",
                    models.PositiveIntegerField(
                        default=8,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "department",
                    models.ForeignKey(
                        db_column="department_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="DB.department",
                    ),
                ),
            ],
            options={
                "db_table": "PROGRAMME_DATA",
                "unique_together": {("programme_code", "batch")},
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "regd_no",
                    models.IntegerField(primary_key=True, serialize=False, unique=True),
                ),
                ("dp_key", models.UUIDField(blank=True, default=None, null=True)),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("mobile", models.CharField(max_length=15)),
                (
                    "gender",
                    models.CharField(
                        blank=True, default="Male", max_length=10, null=True
                    ),
                ),
                ("state_name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "district_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("country", models.CharField(max_length=100)),
                (
                    "prev_degree1_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "prev_degree1_university",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "prev_degree1_gpa",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "prev_degree2_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "prev_degree2_university",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "prev_degree2_gpa",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "blood_group",
                    models.CharField(
                        choices=[
                            ("A+", "A+"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                            ("O+", "O+"),
                            ("O-", "O-"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("birthday", models.DateField(blank=True, null=True)),
                ("batch", models.IntegerField(default=2025)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("detention", "Detention"),
                            ("graduated", "Graduated"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="DB.program"
                    ),
                ),
            ],
            options={
                "db_table": "student",
            },
        ),
    ]
