# Generated by Django 5.2.1 on 2025-06-03 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DB", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=10, unique=True)),
                ("duration_years", models.IntegerField(default=4)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="programs",
                        to="DB.department",
                    ),
                ),
            ],
            options={
                "db_table": "program",
            },
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "regd_no",
                    models.IntegerField(primary_key=True, serialize=False, unique=True),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("state_name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "district_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("Country", models.CharField(max_length=100)),
                (
                    "prev_degree1_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "prev_degree1_university",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "prev_degree1_gpa",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
                (
                    "prev_degree2_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "prev_degree2_university",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "prev_degree2_gpa",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
                (
                    "blood_group",
                    models.CharField(
                        choices=[
                            ("A+", "A+"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                            ("O+", "O+"),
                            ("O-", "O-"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("birthday", models.DateField(blank=True, null=True)),
                ("batch", models.IntegerField(default=2025)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("detention", "Detention"),
                            ("graduated", "Graduated"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="DB.program"
                    ),
                ),
            ],
            options={
                "db_table": "student",
            },
        ),
    ]
