# Generated by Django 5.2.1 on 2025-05-28 08:33

import DB.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DB", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="faculty",
            name="dob",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="faculty",
            name="mobile",
            field=models.CharField(default=0, max_length=15, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="faculty",
            name="faculty_id",
            field=models.CharField(
                max_length=4,
                primary_key=True,
                serialize=False,
                validators=[DB.models.validate_fixed_length],
            ),
        ),
    ]
