# Generated by Django 5.2.1 on 2025-06-03 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DB", "0002_program_student"),
    ]

    operations = [
        migrations.AlterField(
            model_name="program",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
