# Generated by Django 5.2.1 on 2025-05-28 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DB", "0002_faculty_dob_faculty_mobile_alter_faculty_faculty_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="faculty",
            name="gender",
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
