# Generated by Django 5.2.1 on 2025-05-28 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DB", "0003_faculty_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faculty",
            name="campus",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="campus_faculty",
                to="DB.campus",
            ),
        ),
        migrations.AlterField(
            model_name="faculty",
            name="department",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="faculty",
                to="DB.department",
            ),
        ),
    ]
