# Generated by Django 5.2.1 on 2025-06-03 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DB", "0003_alter_program_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="prev_degree1_gpa",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="prev_degree2_gpa",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
    ]
