# Generated by Django 5.2.1 on 2025-06-03 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("DB", "0004_alter_student_prev_degree1_gpa_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="regd_no",
            new_name="regdno",
        ),
    ]
