# Generated by Django 5.2.1 on 2025-06-03 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("DB", "0005_rename_regd_no_student_regdno"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="regdno",
            new_name="regd_no",
        ),
    ]
