# Generated by Django 5.2.1 on 2025-06-03 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DB", "0006_rename_regdno_student_regd_no"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="mobile",
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
