# Generated by Django 5.2.1 on 2025-06-03 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("DB", "0007_student_mobile"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="Country",
            new_name="country",
        ),
    ]
