# Generated by Django 5.2.1 on 2025-06-04 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DB", "0008_rename_country_student_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="faculty",
            name="dp_key",
            field=models.UUIDField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="dp_key",
            field=models.UUIDField(blank=True, default=None, null=True),
        ),
    ]
