# Generated by Django 5.2.1 on 2025-06-04 07:06

import mediahandler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mediahandler", "0002_uploadedimage_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadedimage",
            name="image",
            field=models.ImageField(upload_to=mediahandler.models.rename_uploaded_file),
        ),
    ]
